/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url:
  | /**
       * 导航到应用的首页
       */
  "/pages/index/index"
  | /**
       * 导航到关于页面
       */
  "/pages/about/index"
  | /**
       * 导航到测试页面
       */
  "/pages/test/index"
  | /**
       * 导航到标签页的首页
       */
  "/pages/tabs/home/index"
  | /**
       * 导航到标签页的个人中心
       */
  "/pages/tabs/my/index"
}
interface RedirectToOptions extends NavigateToOptions { }

interface SwitchTabOptions {
  url: "/pages/tabs/home/index" | "/pages/tabs/my/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void
}
